### ISSUE TITLE
ERT shuttle mapping issue.

### ISSUE THREAD

**Issue by benj8560** [BoHBranch/BoH-Bay#1006]
#### Description of issue
All of the ERT shuttle is missing ID locks even the small cell they get.

#### Difference between expected and actual behavior
It's expected to be locked tight so some dumb crew member can't wander in and steal the shuttle or whatever gear you put into it.

#### Steps to reproduce
Walk into the shuttle without* a CC/ERT ID and see that all the doors are public.

#### Length of time in which bug has been known to occur

I recall noticing it some time ago but can't give you any exact time frame.

#### Client version, Server revision & Game ID

Server Revision: 8666802a07b1e1e25c1c9e06eb2ee92c3d896e3b -  - 2020-06-24
Game ID: b7P-c7KG

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by benj8560** [comment]
Told it was fixed closing dis

**Comment by Roland410** [comment]
Reeee, told you not to close it yet.
