### ISSUE TITLE
All polytools do not work

### ISSUE THREAD

**Issue by AtlasRules** [BoHBranch/BoH-Bay#1083]
#### Description of issue

You can't use any polytool, the circuit, surgical or tool ones.

#### Difference between expected and actual behavior

The difference is I don't have my polytool implant.

#### Steps to reproduce
1. Get a robot arm
2. Put a polytool in that arm
3. Spawn, try to use it
4. Cry as you do not have a toolset/surgical kit/whatever the FUCK the circuit one is in your arm

#### Specific information for locating

Just look in chat when trying to use one.

#### Length of time in which bug has been known to occur

Since like, old Hestia, I'm pretty sure

#### Client version, Server revision & Game ID

It do not matter.

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by ProbablyCarl** [comment]
https://github.com/BoHBranch/BoH-Bay/pull/1089
