### ISSUE TITLE
Certain jobs (e.g, engineer) cannot get items like hoodies.

### ISSUE THREAD

**Issue by AtlasRules** [BoHBranch/BoH-Bay#1085]
#### Description of issue

As an engineer, I have hoodie selected under the loadout. I do not spawn with this hoodie.

#### Difference between expected and actual behavior

I expect to get a hoodie. I don't.

#### Steps to reproduce
1. Choose hoodie, and I guess, any other item that has the job below it in red in the clothing menu.
2. Spawn.
3. Check your bag and cry.

#### Specific information for locating

N/A

#### Length of time in which bug has been known to occur

I dunno.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by N8-Toe** [comment]
what branch did you have selected?

**Comment by N8-Toe** [comment]
spoke to them, reason they could not is their character was fleet. who can not take hoodies

Asking this be marked closed
