### ISSUE TITLE
Infantry Access Issue

### ISSUE THREAD

**Issue by Yacobpo157** [BoHBranch/BoH-Bay#1115]
#### Client Version: 514
Server Revision: 1bda2f146bdbe25cca7c6db77323bba060b1a358 -  - 2022-02-05
Game ID: cgl-a46J

#### Yuh

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this]

**Comment by Squigger** [comment]
Infantry are not supposed to have access to the Bridge. They're not some special detail squad with all-access like Blueshields. The Infantry SL is also neither command nor command support.

**Comment by Yacobpo157** [comment]
Okay, if you don't want them to have bridge access, the SL should still have access to the Combat Tech and Medic's lockers and prep area.
