### ISSUE TITLE
Full dark-vision trait for custom species is not working

### ISSUE THREAD

**Issue by NopemanMcHalt** [BoHBranch/BoH-Bay#112]
![image](https://user-images.githubusercontent.com/36963049/70824728-e8e80680-1df3-11ea-8e4a-a03ae50e821f.png)

#### Description of issue
Custom species's Tapeta Lucida Majoris AKA Dark-Vision or Night-Vision trait isn't clearing darkness away.

#### Difference between expected and actual behavior
**EXPECTED:** Custom Species can see in the complete darkness without issues.

**REALITY:** Custom Species can't see jack shit.
#### Steps to reproduce

1. Choose a custom species
2. Add Tapeta Lucida Majoris as positive trait.
3. Get into dark room.
4. Wish you had night-vision goggles instead.

#### Specific information for locating

`modular_mithra\code\modules\mithra\traits*`, perhaps. Else, somewhere in that modular folder.

#### Length of time in which bug has been known to occur

Since Custom Species were added, can't be more specific, at least right now.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: e6f5d1b02cfe7d0900023e8f1f2509dbd42e0160 - dev - 2019-12-13
Game ID: b4G-cvYe
Current map: NTSS Dagon

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/BoHBranch/BoH-Bay/issues)

**Comment by ProbablyCarl** [comment]
Issue carried over from Mithra.
It'll be corrected when I get the time.

Or if someone else jumps to it.
