### ISSUE TITLE
Bearcat Revamp issues.

### ISSUE THREAD

**Issue by Crystal9156** [BoHBranch/BoH-Bay#1275]
#### Description of issue
Left side Ion isn't connected. https://prnt.sc/WiyyYaIGKJON
Medbay APC is upside down. https://prnt.sc/r0M4JU3CBo0n
Cargo shuttle can't actually dock. https://prnt.sc/gV19ZcLW6b6a

#### Difference between expected and actual behavior
Connected.
Right side up.
Make it so the cargo shuttle can actually dock, because it can't when you press the dock button.

#### Steps to reproduce

Look at Bearcat.

#### Specific information for locating
Left side of the bearcat. Medbay, etc.

Bearcat map.

#### Length of time in which bug has been known to occur
Since the new merge

#### Client version, Server revision & Game ID
Server Revision: [4025486be68f5ff38c84dfbf952f123aaa60ea1e](https://github.com/BoHBranch/BoH-Bay/commit/4025486be68f5ff38c84dfbf952f123aaa60ea1e) - - 2022-02-21

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Kaksisilma** [comment]
Old bearcat reverted.
