### ISSUE TITLE
GAS Insuls can't be selected in Loadout.

### ISSUE THREAD

**Issue by GLDoS** [BoHBranch/BoH-Bay#1399]
#### Description of issue
GAS cannot get the 'GAS insuls' from loadout.

#### Difference between expected and actual behavior
Expected: Take funny three fingered gloves, And it spawns them in-game.
Actual: Take funny three fingered gloves, And it just says you cannot spawn with them.

#### Steps to reproduce
Step one: Play GAS.
Step two: Go to Loadout.
Step three: Select GAS Insulated gloves.
Step four: Try to spawn in.
Step five: **Cry Because they weren't given, and you're a Engineer.**

#### Specific information for locating

three-fingered insulated gloves

#### Length of time in which bug has been known to occur
For at least a month now.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: [bbf50a624aa06cf56bd384b2a78e1423614ed643](https://github.com/BoHBranch/BoH-Bay/commit/bbf50a624aa06cf56bd384b2a78e1423614ed643) - - 2022-03-02
Game ID: cgK-c2iz
Current map: SGV Dagon

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Rafflesia7793** [comment]
This appears to happen because the GAS Insuls are not allowed for "Civilian" branches, which is the only branch the GAS can be in. 

![image](https://user-images.githubusercontent.com/100093914/156842591-813c77bb-50d0-497d-9c1c-2aee417964f7.png)

**Comment by Rafflesia7793** [comment]
allowed_branches should be allowed_roles.

![image](https://user-images.githubusercontent.com/100093914/156843228-ad6873fc-54cd-473d-95c8-f9526ded3d6c.png)
