### ISSUE TITLE
Vattie names can't have numbers

### ISSUE THREAD

**Issue by Keekenox** [BoHBranch/BoH-Bay#1433]
For some reason after you edit a vat grown human, their name will no longer be able to have numbers in it, despite being able to put them there when you first switch to vat grown human.

When you try and add the numbers it will just leave them blank like this. [https://i.imgur.com/fu5N2tw.png](url)

**Comment by Keekenox** [comment]
I think it might have something to do with having your backround not set to nonborn. Kinda stupid if I'm being honest.

**Comment by N8-Toe** [comment]
yeah, Nonborn is flagged to allow numbers in names. You'll need that to have a number in there
