### ISSUE TITLE
Ammo States missing for the P20 Pistol and MA-Pariah SMG

### ISSUE THREAD

**Issue by BurpleBineapple** [BoHBranch/BoH-Bay#1485]
#### Description of issue

The P20 pistol and Pariah SMG both lack ammo indicators in their icons

#### Difference between expected and actual behavior

The SMG should have its magazine visible decrease as it is fired, and should have an 'empty' state when unloaded. It always looks like it's full in the UI however.

The P20 Pistol has what should be a blue light on its frame that turns red as the ammo count decreases. This does not work either.

#### Steps to reproduce

Take a P20 pistol or Pariah SMG, fire it, notice nothing changes.

#### Specific information for locating

 SMG path is obj/item/weapon/gun/projectile/automatic/sec_smg/less_lethal

P20 path is obj/item/weapon/gun/projectile/pistol/military

#### Length of time in which bug has been known to occur

At least as long as the Pariah was introduced. P20 I'm not sure.

#### Client version, Server revision & Game ID

Server Revision: [e949b98d60d0cf6f2bfceac3c6453b3fbf61e309](https://github.com/BoHBranch/BoH-Bay/commit/e949b98d60d0cf6f2bfceac3c6453b3fbf61e309) - - 2022-03-10
Game ID: cgT-a6Y2

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/BoHBranch/BoH-Bay/issues)

**Comment by N8-Toe** [comment]
thanks for opening an issue. I'll look into this

**Comment by BurpleBineapple** [comment]
Fixed
