### ISSUE TITLE
Computer Frames do not have icons

### ISSUE THREAD

**Issue by BurpleBineapple** [BoHBranch/BoH-Bay#1535]
#### Description of issue

Computer frames made with steel sheets and those scattered in maintenance do not have icons

#### Difference between expected and actual behavior

They should have icons, they do not

#### Steps to reproduce

Look at a computer frame built from steel sheets, realize you can't because it doesn't have an icon.

#### Specific information for locating

'computer frame' is the object name

#### Length of time in which bug has been known to occur

At least a few days. This is a relatively new bug.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: [bca93da19e621aaaae865c3e7f53f761e024ab61](https://github.com/BoHBranch/BoH-Bay/commit/bca93da19e621aaaae865c3e7f53f761e024ab61) - - 2022-03-13
Game ID: cgX-bvFz

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/BoHBranch/BoH-Bay/issues)

**Comment by ghost** [comment]
I did this.
