### ISSUE TITLE
invisible wall here

### ISSUE THREAD

**Issue by gilvian** [BoHBranch/BoH-Bay#1583]
![image](https://user-images.githubusercontent.com/13832819/159020025-4bd8de2b-1c74-4f5a-81fa-bad5eb525a22.png)

**Comment by N8-Toe** [comment]
issue is repeatable on live server

its connected to the sulph acid dispenser, can traverse the tile once it is deleted

**Comment by gilvian** [comment]
yeah sadly nobody can fix it currently since only Kak can fix it with his horrible medbay rework

**Comment by N8-Toe** [comment]
has been fixed
