### ISSUE TITLE
N8-Toe Post it board

### ISSUE THREAD

**Issue by Plaguewalker** [BoHBranch/BoH-Bay#1584]
#### Description of issue
N8 TOE HERE'S YOUR FUCKING ISSUE YOU ASKED

#### Difference between expected and actual behavior
POST YOUR ISSUES HERE

#### Steps to reproduce
1.Speak to N8-Toe
2.Remind them of issue
3.Expect them to forget a day later
4.Repeat

#### Specific information for locating
Github

#### Length of time in which bug has been known to occur
1980's-2020s

#### Client version, Server revision & Game ID
 N/A
#### Issue bingo

- [x ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/BoHBranch/BoH-Bay/issues)

**Comment by N8-Toe** [comment]
:c

**Comment by gilvian** [comment]
https://user-images.githubusercontent.com/13832819/159020460-5f00680f-597f-4ca5-8513-2147fcdfec98.mp4

**Comment by InfinitelyThinRectangles** [comment]
![laughter7](https://user-images.githubusercontent.com/55716285/159020558-66d3cfcb-23d9-41be-9864-51022fcf0bf1.gif)

**Comment by Plaguewalker** [comment]
![dfeew](https://user-images.githubusercontent.com/26019993/159020786-9e93b8ea-c625-4710-a6ca-312dbc22e013.PNG)

**Comment by Cupax3** [comment]
This is rather insulting.

**Comment by Anton-Kr** [comment]
Issue yourself some bitches
