### ISSUE TITLE
Armalis/GAS grabs paralyze you for an indeterminate amount of time, even after they've let go

### ISSUE THREAD

**Issue by AtlasRules** [BoHBranch/BoH-Bay#1626]
#### Description of issue
If you're nabbed by an armalis or GAS, you're paralyzed for some amount of time, even after they've let go, either intentionally or from being forced to let go.

#### Difference between expected and actual behavior

You should be able to move after being let go. But you can't.

#### Steps to reproduce

1. Get nabbed by a Vox Armalis or GAS
2. Get let go.
3. Wonder why you CAN'T FUCKING MOVE OR DO ANYTHING.

#### Specific information for locating

N/A

#### Length of time in which bug has been known to occur

Probably since their grabs got buffed.

#### Client version, Server revision & Game ID

It do not matter.

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/BoHBranch/BoH-Bay/issues)

**Comment by Armyguy** [comment]
Its a determinate amount of time, and its not a bug. GAS nab has Stun(3), and armalis Stun(15).

**Comment by AtlasRules** [comment]
if it’s not a bug then it fucking sucks lmfao

**Comment by Anton-Kr** [comment]
so make a pr to change it stinky

**Comment by AtlasRules** [comment]
> so make a pr to change it stinky

![]https://preview.redd.it/t7dcqqmq67781.jpg?auto=webp&s=0118b2aca68435f0138ad24ffde55905115bc7cb

**Comment by AtlasRules** [comment]
> so make a pr to change it stinky

![01707469-5F16-4CFE-8F5D-6CB6BBADA60E](https://user-images.githubusercontent.com/49167264/160100004-197aa773-0977-441e-9482-4e255be2fa4d.jpeg)
