### ISSUE TITLE
Cryogenic Freezers in pods are missing sprites.

### ISSUE THREAD

**Issue by GrayRachnid** [BoHBranch/BoH-Bay#171]
#### Description of issue
Title
![image](https://user-images.githubusercontent.com/6613514/71127876-ebfb4200-21b9-11ea-8bce-c28d7c801c55.png)

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by GrayRachnid** [comment]
![image](https://user-images.githubusercontent.com/6613514/71128025-544a2380-21ba-11ea-85f8-d6b369747983.png)

**Comment by Michiyamenotehifunana** [comment]
The cryogenic freezers need to be rotated to show up. For some reason the icon state doesn't have a north-facing sprite, IIRC.

**Comment by BurgerLUA** [comment]
I believe this was fixed in a PR? Not sure, because latest version of dev doesn't seem to have this issue.

**Comment by BurgerLUA** [comment]
Yeah this was fixed in some PR. Closing.
