### ISSUE TITLE
Need more permanent fix to travis

### ISSUE THREAD

**Issue by ghost** [BoHBranch/BoH-Bay#29]
See: title

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by MarinaGryphon** [comment]
Fix completed. Please close.
