### ISSUE TITLE
Inaccurate placement of Items on Tables

### ISSUE THREAD

**Issue by Subosovitch** [BoHBranch/BoH-Bay#350]
### Description of issue
Cannot place a item with accuracy on the table. Will always revert to semi-random default position making everything into a giant pile per tile.

#### Difference between expected and actual behavior
Items should be there where you click to allow arrangement of items without making a giant pile of doom.

#### Steps to reproduce
1. Take item
2. Place on desk
3. Notice its not where you clicked.

#### Specific information for locating
Any Object
Any Table

#### Length of time in which bug has been known to occur
~48 Hours

#### Client version, Server revision & Game ID
Client Version: 512
Server Revision: 571ba4d960dbe807b8cb6e836395063a56b8950d - dev - 2020-02-06
Game ID: b5z-aIjN
Current map: NTSS Dagon

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this (https://github.com/BoHBranch/BoH-Bay/issues)

**Comment by Andromeda-K22** [comment]
Has to do with Bay's 'center of mass' system for items. Tables have a strange invisible grid that items snap to, because ... baystation.

**Comment by Andromeda-K22** [comment]
Can't be fixed without fucking up a lot of other stuff.

**Comment by Subosovitch** [comment]
I mean it was working properly a day or two before it was added and on bay it still works properly.

But sure.
