### ISSUE TITLE
Veteris Unathi Sprint Speed and Regeneration.

### ISSUE THREAD

**Issue by EldritchSigma** [BoHBranch/BoH-Bay#406]
Description of issue:

Sprinting as Veteris'Unathi basicly lets you run at TG speed. I know other races speed and its not nearly as fast. Sergals might be at the same speed I believe. This is definitly not intended behavior since they are supposed to be slow like regular Unathi. Perhaps a bit faster but they are currently outrunning everyone. Secondly I believe the regeneration is comically strong. Not sure if other factors were in there but the wounds mended at a much faster rate than what I am used to from regular Unathi.

Difference between expected and actual behavior

Not having comical speed when sprinting while wearing armor. Not having comical regeneration. Uncertain if other things factored into the regen.

Steps to reproduce

Pick Veteris'Unathi. Get hurt. Watch regen.
Pick Veteris'Unathi. Sprint. Observe sprint speed that might be absurdly high.

**Comment by BurgerLUA** [comment]
I'll have to do further testing. I copied the speed values from regular unathi. Unathi also share the same regen so I don't know what's going on here.

**Comment by EldritchSigma** [comment]
Regen seems to be fine right now. Dunno what made it spazz out back in that round. Sprint speed still feels rather insane.

**Comment by BurgerLUA** [comment]
I think the regeneration needs to be nerfed in the future, yes.

**Comment by BurgerLUA** [comment]
Closing due to it not being a bug. Regeneration will probably need to be nerfed in the future upon the community's approval.
