### ISSUE TITLE
Veteris Unathi cannot wear voidsuits

### ISSUE THREAD

**Issue by miniusAreas** [BoHBranch/BoH-Bay#459]
At the time of this PR I'm unsure if the cause is player incompitence or they can't actualy wear voidsuits, but after cycling a suit and attempting to have a player wear it, they're unable to put it on or have it forced on. Please save me from this anurism.

**Comment by Chaznoodles** [comment]
This is unclear. 

What happens when they attempt to wear a voidsuit? Does a feedback message appear in the chatbox? Is it reproducible over multiple rounds by different players? Did they try to wear different kinds of species voidsuit to see if any fitted?

**Comment by miniusAreas** [comment]
No message appeared from forcing it on, was unable to gleem anything useful from the player themselves. Tried every species in the cycler. I'll try other suits and doing it myself soon.

**Comment by BurgerLUA** [comment]
This was fixed in #512
