### ISSUE TITLE
Nacelle Combustion Chamber Walls(OCP Walls) have the same melting point as Plasteel walls, which is a joke for SS13 combustion.

### ISSUE THREAD

**Issue by GrayRachnid** [BoHBranch/BoH-Bay#462]
#### Description of issue
The nacelle walls cannot hold when the fuel mode is switched over to combustion

#### Difference between expected and actual behavior
Expect nacelle walls to hold while combustion is ongoing

#### Steps to reproduce
Flip fuel mode over, ignite. Watch as the walls burn down. Keep in mind that you should also be using the combustion fuel that you make from the combustion or the walls are going to burn down regardless. 

The issue is that the walls burn down even while the fuel is being used.

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by BlueNexus** [comment]
Hi, I added OCP and the nacelles, this is a bug - They're meant to take 12,000K.
