### ISSUE TITLE
Sergal FBP's that are freshly constructed only speak sergal

### ISSUE THREAD

**Issue by miniusAreas** [BoHBranch/BoH-Bay#481]
Says it all in the name. A sergal that was de-brained, MMI'd, and put in a FBP that was for sergals could only speak Sergal, and not ZAC.

**Comment by Eonoc** [comment]
Other species of FBP will often either have no languages at all, or just racial defaults. Humans have none. Unathi have Sinta only, etc.

**Comment by Roland410** [comment]
Sergals were rolled into genemodders, so this should not be an issue anymore.
