### ISSUE TITLE
Psionic telekinesis is broken

### ISSUE THREAD

**Issue by Knightfall5** [BoHBranch/BoH-Bay#496]
#### Description of issue 
You can use psionic telekinesis to grab people from range, and then repeatedly slam them into nearby objects for massive damage as shown here. 

https://imgur.com/a/b3xhNxH

Regardless of what object you slam them into it does enough damage to explode limbs and is fully capable of one-shot exploding someone's head or lower body, and since you can rapidly spam it it is basically an assured kill every time.

#### Difference between expected and actual behavior
I assume it should behave like a regular grab and not be a weapon of mass destruction.

#### Steps to reproduce
Grab someone with psionic telekinesis, slam into nearby objects.

#### Specific information for locating

https://github.com/BoHBranch/BoH-Bay/blob/8bc68fd6b9e29fdc730ccf6507ea1cecad75ca73/code/modules/psionics/equipment/psipower_tk.dm

#### Length of time in which bug has been known to occur

No idea.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 67eddf5d4a8e15533cf6f941fab409d19f92b2e9 -  - 2020-03-02
Game ID: b5Z-agBm

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by BurgerLUA** [comment]
I think it's an intended feature, however it's a balance issue.

**Comment by BurgerLUA** [comment]
It's a balance issue. Someone needs to nerf it in the future.

**Comment by chaoko99** [comment]
Only paramounts can do this.
