### ISSUE TITLE
Impossible to open maintenance panel of kitchen oven

### ISSUE THREAD

**Issue by Cairo283** [BoHBranch/BoH-Bay#592]
#### Description of issue

It's impossible to use a screwdriver to open the maintenance panel of the oven in the kitchen. Clicking on it with a screwdriver just opens the panel then closes it again, even if you only click once.

#### Difference between expected and actual behavior

To open the maintenance panel to replace the parts.

#### Steps to reproduce

Click on an oven with a screwdriver.

#### Specific information for locating

oven

#### Length of time in which bug has been known to occur

For at least a month now, though I assume since the oven was added.

#### Client version, Server revision & Game ID

43581bfd758a8b4d3b49354167dafbac795cbe1d -  - 2020-03-24

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by MarinaGryphon** [comment]
Was it open or closed?

**Comment by Cairo283** [comment]
> Was it open or closed?

It starts closed, but using a screwdriver on it, even clicking once, opens it then closes it again right away.

**Comment by Cairo283** [comment]
Alrighty, just tested this the other day, and it seems to have been fixed! Thanks whoever did that. Closing.
