### ISSUE TITLE
Issue: Ascent Drones do not have ZAC

### ISSUE THREAD

**Issue by MemedHams** [BoHBranch/BoH-Bay#597]
#### Description of issue
The Ascent Drones, despite being advanced alien technology, are the only ascent incapable of understanding human speech. 

#### Difference between expected and actual behavior
Ascent Drones, being a highly advanced piece of alien tech, even when entirely brainless, should probably have the ability to translate languages like the other ascents, who have this ability due to their translation implant.

#### Steps to reproduce
Choose ascent drone during a seedship round. Attempt to ask primitive in person why they are so stinky and gross. Weep because you are apparently less powerful then a tape recorder. 

#### Specific information for locating
N/A, role related. 

#### Length of time in which bug has been known to occur
N/A, state of painful existence

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by BurgerLUA** [comment]
Not sure if this is a bug or a feature.

**Comment by MemedHams** [comment]
Really, the best fix for this would be giving ascent drones inherent translation properties, like the ones given by the translator implant(which all other ascent have)

**Comment by reklaw9** [comment]
Im almost sure that this was already fixed.

**Comment by Roland410** [comment]
Fairly sure this was fixed. Let me know if not.
