### ISSUE TITLE
Vox Slugs attack Armalis 

### ISSUE THREAD

**Issue by MemedHams** [BoHBranch/BoH-Bay#606]
#### Description of issue
Armalis, despite being vox, trigger the bloodlust of the genetically engineered mobile bite dispensers they use to make humans wet themselves.
Ingame, some players supposed this may be because Armalis do not have the simplemob Vox faction, for some reason. 

#### Difference between expected and actual behavior
Vox slugs are supposed to be passive to all vox. They are not.

#### Steps to reproduce
1: Be armalis
2: Use slug sling
3: Cry when your babies betray you

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by MemedHams** [comment]
Finally played armalis again, lil' buggers still try to eat you

**Comment by Roland410** [comment]
Fairly sure this was fixed in the remap of the voxship.

**Comment by Roland410** [comment]
This was already fixed.
