### ISSUE TITLE
Ascent Landing Ships cannot land on planets.

### ISSUE THREAD

**Issue by MemedHams** [BoHBranch/BoH-Bay#610]
#### Description of issue
The ascent Seedship's shuttles, the Lepidoptera and the Trichoptera, cannot land on most planets.

#### Difference between expected and actual behavior
As you can imagine, being unable to land on the surface of the planets you intend to colonize makes colonization somewhat difficult.

#### Steps to reproduce
1: Spawn in as ascent
2: Rush to beat the Dagon to a nearby forest planet so you can claim it for your hive
3: Succeed and realize it doesn't matter anyway. Existential crisis about your purpose optional but suggested. 

#### Specific information for locating
Try to bring one of the shuttles onto the planets using their shuttle console. 

#### Length of time in which bug has been known to occur
During rounds the ascent spawn in. 

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by MemedHams** [comment]
Added "Could be reproduced in different rounds" check.

**Comment by MemedHams** [comment]
When I say most planets, I should elaborate: Most prefab planets like the snowy away mission are fine, but the randomly generated planets(the most common ones) cannot be landed by the Lepi or Trichop, the ascent landers.

**Comment by Roland410** [comment]
This is caused by mountains spawning/other ships taking up the possible landing spaces, and occurs with all shuttles.
If this still happens specifically to Ascent ships let us know and we'll reopen this.
