### ISSUE TITLE
Weapons lathe requires materials it can't accept

### ISSUE THREAD

**Issue by Cairo283** [BoHBranch/BoH-Bay#619]
#### Description of issue

The weapons lathe requires "mutagen", a chemical, to produce a decloner ray which is unlocked at very high levels. However, since the machine is based on an exosuit fabricator, it can't actually accept the mutagen, resulting in the weapon being unable to be made.

#### Difference between expected and actual behavior

To be able to click on the weapon's lathe with a full beaker to load it in, or for the weapon to not involve a chemical at all, and just use uranium instead. 

#### Steps to reproduce

Get weapon's research to level nine, sync the weapons lathe, and try to click on the machine with a beaker of any chemical. Nothing happens.

#### Specific information for locating

weapons lathe

#### Length of time in which bug has been known to occur

I know this happened when weapons could be produced in the Protolathe, as well, so I assume this has been a problem since the decloner itself was added to the production list.

#### Client version, Server revision & Game ID

0a8eef42b9f4539d90ef50061265389030676397 -  - 2020-03-26

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Roland410** [comment]
The weapon was already removed from it to my knowledge, let us know if it's still an issue.
