### ISSUE TITLE
Perma brig doors are ID locked.

### ISSUE THREAD

**Issue by Sparrowbird611** [BoHBranch/BoH-Bay#626]
#### Description of issue

The doors in the permanent holding cell, namely the head and bedroom doors, appear to be ID locked to security.

#### Difference between expected and actual behavior

You wouldn't think I'd need to call security over every time I wanted to get into my bedroom, or go to the bathroom.

#### Steps to reproduce

Run the game, and test the security brig doors with a security ID card and a non security ID card.

#### Issue bingo

- [yes] Issue could be reproduced at least once
- [yes] Issue could be reproduced by different players
- [yes ] Issue could be reproduced in multiple rounds
- [yes] Issue happened in a recent (less than 7 days ago) round
- [yes] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Roland410** [comment]
iirc I fixed this in the FADV PR, should be checked again tho.

**Comment by Sparrowbird611** [comment]
The doors are fixed from what I've seen, though I noticed the brig lockers are still ID locked. Not sure if that's intentional or not.

**Comment by Roland410** [comment]
The lockers are to put prisoners' stuff by security.

**Comment by Sparrowbird611** [comment]
Seems slightly odd to do so in perma brig. I would think it would go into evidence storage in that case.

**Comment by Roland410** [comment]
I should have fixed this for real in the legal PR. Let me know if not.
