### ISSUE TITLE
Drones are not properly aligned with the movement grid. 

### ISSUE THREAD

**Issue by MemedHams** [BoHBranch/BoH-Bay#628]
#### Description of issue
Drones, both Dagon Synthetic and Ascent Control Intelligence, have had their movement grid placement somehow messed up.
<img width="128" alt="my pain" src="https://user-images.githubusercontent.com/45698967/78194048-0647eb80-744a-11ea-870c-d914a6c7c22d.PNG">
As you can probably see, drones tend to be anywhere from 30-60% on the tile immediately leftwards of them, visually. This is mostly asthetic but is annoying as hell.

#### Difference between expected and actual behavior
Local drone violates the grid-based laws of reality. PUT ME BACK INSIDE THE SQUARE, I HAVE SEEN THINGS I CANNOT COMPREHEND

#### Steps to reproduce
1:Be drone
2:Violate the laws of alignment and transcend space and time.
3:Ì̷̜ ̶̢́A̸̝͌M̷̬̓ ̶̪͌B̶̺͗E̵̞̽Ȳ̸̙O̶̡̿N̵͈̚D̵̠̑ ̸̮͘T̷̰͗H̵̘̓E̴̲͘ ̵̯̃W̸̪͌A̴̱͂Ľ̸̩L̸͇͊S̷̞̑ ̷̠͐Ȯ̷̜F̶̗͝ ̶̯͋S̵̺͋P̶̤͑Ạ̵̈C̶̱͝E̴͎̎ ̵̧͌A̵͚̓N̶̤̎D̸̢̆ ̴̛̟T̴̫̅I̶̡͒M̸̙̚Ė̴̯,̸̫͐ ̸̗͛G̵̡̀R̴̤͗Ȁ̷̟V̷͕͊Ì̸̧T̶̮̉Y̷͓͋ ̸̯̅I̵̩͊Ş̸̀ ̴̖̍D̸̢͝E̶̹͌S̵͎̾I̶̝̓R̷̡̐E̴̖̚,̷̩̋ ̴̳̎E̷͕͑N̵͙͐Ṯ̴̀R̷͍͝O̶̤͒P̸̡̀Y̴̫̔ ̸̥͛Į̵̈S̵͚̓ ̶̼̕H̸̱͊U̵̜̇N̸͇̏G̴̺̓È̵̘R̴̜̈.̷̪̃ ̵̖̎N̴̩̕O̷͙͛T̶̹̃H̸̪̔Ị̸͆N̵̝̽G̸̛̺ ̴͓͆A̸͕͊W̷̨͠A̶͜͠I̴̦̓Ț̵̄S̷͔͐ ̸͈̉M̴̠̍E̸̢͛ ̴̩̊B̷̫̍Ư̴͓T̷͉̎ ̵͍̔E̵͍͠Ṋ̶̽D̵̯͂L̷̩̚E̴͕͋S̶̮͌S̶̗̾ ̶̹̉D̷̺̃E̴̡̛A̶̬͂T̸̼̒H̵̡̆.̴̺̐

#### Length of time in which bug has been known to occur
Today, and yesterday. 

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

H̸̛̦̿́͌ȩ̸̩̠͓̻͇̏͛́͐͗̇͒̚͠l̵̨̧͔̤̝̰̼̣̪̟̲̯̖͉̞̮̜͙̠̮̫͒p̵̠̰̌̈́̇̅ ̸͍̩̟̬̻̟̳̘̼͓̻͇̂͑͂̏́̓̕ͅm̵̢̡̡̢̛̲̝͚̺̗̮͓̯͕̖͇͚̖̪̠̥̬̪̹̦̬̔̿́e̵̢͉̥͚͙̳͚̜̹̩̱̩̼̯̟̜̰̻̒̃̆̔̅̽̈́͒̃̍̐͌̈́

**Comment by MLGTASTICa** [comment]
Also had this bug , it fixes itself after you hit anything as a cyborg .

**Comment by BurgerLUA** [comment]
The only reason why this would occur is because dogborgs are still in. Does this still occur?

**Comment by MemedHams** [comment]
update: this no longer occurs
