### ISSUE TITLE
NSFW Flavor text is not saved.

### ISSUE THREAD

**Issue by JohnBigless** [BoHBranch/BoH-Bay#670]
#### Description of issue
Upon clicking 'Save Slot' in the character customization menu, anything written in the Flavor Text section under *Naked (NSFW)* is removed/not saved.

#### Difference between expected and actual behavior
Expectations: NSFW flavor text will be saved just fine.
Reality: NSFW flavor text is not saved.

#### Steps to reproduce
Step 1: Go to Character Setup (Doesn't matter if entered during a round or trough the main menu)
Step 2: Go to Set Flavor Text
Step 3: Click *Naked (NSFW)* and write anything in it.
Step 4: Click 'Save Slot'
~~Step 5: Load the saved slot.~~ (Seems like just clicking Save Slot is enough to reproduce the bug.)
Step 6: Paragraph describing your character's pp is now gone.

#### Specific information for locating

N/A, the Character Setup screen is not an object or outputs any log messages.

#### Length of time in which bug has been known to occur

8th of April, 2020, 16:33.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 5a0f988ca5faeee1cb8375f078b6371a7dd21675 -  - 2020-04-08
Game ID: b6z-cmrR (Not accurate. Game ID was taken after the previous round crashed.)
Current map: NTSS Dagon

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by BurgerLUA** [comment]
This issue needs confirmation by more than one player.

**Comment by JohnBigless** [comment]
http://prntscr.com/rwyzk0
That settles it.

**Comment by BurgerLUA** [comment]
Being fixed #681
