### ISSUE TITLE
The mini energy crossbow isn't actually mini

### ISSUE THREAD

**Issue by Cairo283** [BoHBranch/BoH-Bay#674]
#### Description of issue

The mini energy crossbow is actually a normal-sized item, and doesn't fit in your pocket or a holster.

#### Difference between expected and actual behavior

With it being called "mini" energy crossbow, and it being a small item in literally every other server, AND its codex description saying, verbatim, "can be concealed in your pocket or bag", one would assume it could fit in your pocket, but it cannot. 

#### Steps to reproduce

Be a traitor, order the crossbow, try to put it in your pocket. Or be a renegade and have it spawn in your backpack. Or just spawn it as an admin because you're lazy.

#### Specific information for locating

mini energy-crossbow

#### Length of time in which bug has been known to occur

No idea.

#### Client version, Server revision & Game ID

a8b3ed5bc963b8d6afa95d1663165732eafe5984 -  - 2020-04-09

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by SilvernKell** [comment]
https://github.com/BoHBranch/BoH-Bay/pull/675

Someone fixed this! Was fast.

**Comment by Cairo283** [comment]
Good times, closing, then.

**Comment by chaoko99** [comment]
It hasn't been merged yet!

**Comment by Cairo283** [comment]
Well it's *about to be* so that's good enough.
