### ISSUE TITLE
Cannot set NSFW flavor text trough Set-Flavour-Text verb.

### ISSUE THREAD

**Issue by JohnBigless** [BoHBranch/BoH-Bay#688]
#### Description of issue
*Naked (NSFW)* flavor text setting option is not present in the *Set-Flavour-Text* verb.

#### Difference between expected and actual behavior
Expectations: Be ability to set my character's NSFW flavor text mid-gameplay just fine.
Reality: The old OOC/NSFW option is present instead.

#### Steps to reproduce
Step 1: Be ingame.
Step 2: Use the *Set-Flavour-Text* verb,
Step 3: 
![image](https://user-images.githubusercontent.com/44721288/79047029-8faea900-7c14-11ea-8d00-0139644cc049.png)

#### Specific information for locating

N/A

#### Length of time in which bug has been known to occur

Initially discovered on a private server a couple days ago. Succesfully reproduced results in 11th of April, 2020. 16:47

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: ac76e681649a45e6fcb267c7bb2734837547e310 -  - 2020-04-11
Game ID: b6C-b3fj
Current map: NTSS Dagon

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by TheOrleans** [comment]
Working on it, probably fixed, Will be learning how to make a PR and mentioning it here in around 30m
