### ISSUE TITLE
Cable coil produced by autolathe is normal-sized

### ISSUE THREAD

**Issue by Cairo283** [BoHBranch/BoH-Bay#690]
#### Description of issue

Cable coil, when made in an autolathe, is a normal-sized item, when cable coil that spawns normally is small/tiny.

#### Difference between expected and actual behavior

For the cable produced by the lathe to be small/tiny.

#### Steps to reproduce

Select cable coil in the autolathe menu, let it be built. Examine it/try to put it in your pockets.

#### Length of time in which bug has been known to occur

Since the autolathe's menu was changed, I'm pretty sure.

#### Client version, Server revision & Game ID

ac76e681649a45e6fcb267c7bb2734837547e310 -  - 2020-04-11

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Cairo283** [comment]
May I also add to this that's hella annoying to click on the constantly moving cable coil button thirty times to get a stack? Unrelated to the bug, but we really need a button on the autolathe to queue more than one thing at a time, like a x5 and x10 button next to the items we want to produce.

**Comment by TheOrleans** [comment]
Working on it, I think I will be able to finish it tonight
