### ISSUE TITLE
10mm rubber magazine box should be in the general armoury 

### ISSUE THREAD

**Issue by Jackofashepard** [BoHBranch/BoH-Bay#693]
Currently the 10mm rubber magazine box is in the secure armoury making it a hassle to get to unless you have a very willing COS or brig chief

**Comment by BurgerLUA** [comment]
Not really a bug I don't think. Someone can PR this if the wish it change it.

**Comment by Roland410** [comment]
As per above, a PR should be opened to change this (although I think they were moved out to equipment storage).
