### ISSUE TITLE
'empty basket' trash item has no sprite.

### ISSUE THREAD

**Issue by JohnBigless** [BoHBranch/BoH-Bay#706]
#### Description of issue
A trash item, 'empty basket' is lacking a sprite.

#### Difference between expected and actual behavior
Expectations: Be able to see the basket normally.
Reality: Sprite machine broke.

#### Steps to reproduce
Step 1: Take a stroll into maintenance
Step 2: 
![empty basket no sprite](https://user-images.githubusercontent.com/44721288/79380258-797c5200-7f60-11ea-8458-24957f952a42.png)

#### Specific information for locating

/obj/item/trash/chipbasket

#### Length of time in which bug has been known to occur

Seen this bug several times, only now i could be bothered to report it.
Bug last reproduced 15.4.2020 21:28

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: bf795d382422251e8ccdcf109262f7f76778cc2b -  - 2020-04-15
Game ID: b6G-c6Wk (Innacurate.)
Current map: NTSS Dagon

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Cairo283** [comment]
I can confirm that this is a bug. Along with that, the trash item "square tray" also lacks a sprite.

**Comment by JohnBigless** [comment]
I did some code digging, the `"chipbasket_empty"` sprite that the empty basket is supposed to use is non-existent. Same goes with the square tray that uses the `"brownies"` sprite. Once again, non-existent.
