### ISSUE TITLE
HCM Hardsuits don't work for IPCs

### ISSUE THREAD

**Issue by SilvernKell** [BoHBranch/BoH-Bay#745]
#### Description of issue
HCM cannot be deployed if you are of the machine race. This is a thing that has happened on bay since forever. It might have been intended, but it's also stupid. They work fine on fbps too.

#### Difference between expected and actual behavior

I expect IPC to be able to use a HCM, especially since they can have coolers in them.

#### Steps to reproduce
Wear a HCM and you are unable to deploy any of the constituent parts or activate the suit.

#### Length of time in which bug has been known to occur

Forever, thanks Bay reee

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Roland410** [comment]
I should have fixed this a while ago, let me if this is still an issue.
