### ISSUE TITLE
Right-click menu actions not functional.

### ISSUE THREAD

**Issue by WatermelonsEverywhere** [BoHBranch/BoH-Bay#787]
#### Description of issue
Using the right-click menu to perform an action doesn't work, except for "Examine" and "Point To", for example, trying to take out a Pen from a PDA using the right-click menu turns up an error.

Sorry, the following is not valid: PDA
usage: Remove-Pen obj`

#### Difference between expected and actual behavior
Expected - The pen to be removed from the PDA.

Actual - Nothing happened.
#### Steps to reproduce
1.- Get any object that has an action other than Examine or Point To when right-clicked.
2,- Try to perform said action.

#### Specific information for locating
Unsure.

#### Length of time in which bug has been known to occur
At this exact moment, 5/1/2020, bug was known not to occur atleast 19 hours ago, which is when I last played, and successfully pulled out a pen from a PDA.

#### Client version, Server revision & Game ID
Client Version: 513
Server Revision: 486a03cc28d7452af75b366dc6055b0d2274f507 -  - 2020-04-30
Game ID: b6W-dpYc

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Allfd** [comment]
I can confirm this exists.

This is due to a bug in byond version 513.1521

A workaround is to use version [513.1520](http://www.byond.com/download/build/513/513.1520_byond.exe) and not update until it is fixed.

**Comment by BurgerLUA** [comment]
It's a byond issue. Can't fix this on our end.

**Comment by WatermelonsEverywhere** [comment]
Fixed as of BYOND version 513.1522
