### ISSUE TITLE
Kharmaan Alate Limb transplant  bug

### ISSUE THREAD

**Issue by reklaw9** [BoHBranch/BoH-Bay#878]
#### Description of issue
okay so,if you lose a limb as a kharmaan alate,you cant get a new limb unless you get ahealed,limbs from bioprinter doesnt work too

#### Difference between expected and actual behavior
finding a bioprinter,putting your blood on it,printing your own lost limb,getting someone to put it on you,you have all of your limbs now

finding a bioprinter,putting your blood on it,printing your own lost limb,getting someone to put it on you,oh wait,my own limb made of crystal is a "flesh limb"
#### Steps to reproduce
lose your limb somehow->get a saw and cut the stump of your limb ->get a bioprinter -> get a syringe and put your blood on the syringe -> inject the blood on the syringe into the bioprinter -> make the limb that you lost -> get a OPTABLE and someone to insert the limb on you ->you cant

#### Length of time in which bug has been known to occur
i discoved this 1-3 days ago

#### Issue bingo
- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]

NOTE:on my case when i discovered that,i lost my right hand (right grasper) ingame because the gyne ate it

**Comment by Vizoplez** [comment]
Resolved via ascent bath water update.
