### ISSUE TITLE
Beards are no more.

### ISSUE THREAD

**Issue by TheOrleans** [BoHBranch/BoH-Bay#911]
#### Description of issue
Beard UI in character setup is not loading, and in mirrors, beards are not loading either. This issue came out from one round to the next one, it was working some hours ago

#### Difference between expected and actual behavior
Beards should be in the game, but they aren't. We can say BoH has killed beards, beards are no more.

#### Steps to reproduce
Open character setup, click on facial styles button. Click on mirror, scroll down.
https://i.gyazo.com/cce062285fce5ba8bf10d6ab19802ce3.png
#### Specific information for locating
Facial hair UI

#### Length of time in which bug has been known to occur
This round. Torque and I worked on it and it today, cause I just noticed. However, this was said by another player:  HungryCricket: that shits bugs for me all the time

So maybe it's going for a longer time, who knows
Client Version: 513
Server Revision: ba6371a31fa820ff25aae492122ec8a0e4709861 -  - 2020-05-22
Game ID: b7j-aM4k

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this] 
I found it: https://github.com/Baystation12/Baystation12/issues/20915 
It gets reported every now and then, it's strange, because it seems it only happens on some rounds... no idea

**Comment by Roland410** [comment]
Yeah, this sure is a strange bug that never gets tracked down because of how unreliably it happens.

**Comment by MarinaGryphon** [comment]
The issue happens on Aurora as well, for both hair and facial hair. It appears to be an issue with using unstable BYOND versions.

**Comment by dnworden** [comment]
Not sure if this is the intended context, but I have found a way to reproduce the bug:

1. Start as male, use Quickee's Plastic Surgeon or the Change Mob Appearance command to change your facial hair.
2. Use the menu to change to female, select the 'Shaved' facial hair option (which should be the only option).
3. Change back to male, and the facial hair options should not reappear (this is the bug).
