### ISSUE TITLE
Vasilissans are not radiation proof

### ISSUE THREAD

**Issue by TheLordME** [BoHBranch/BoH-Bay#918]
#### Description of issue
The Vasilissan Species is a radiation proof, human sized spider, that is infact not radiation proof.

#### Difference between expected and actual behavior
Characters that are from the Vasilissan species should be radiation proof, a quick visit to the engine room without proper PPE lead to discomfort (the 100 disappeard from the figure on the rightside) like with a human.
Secondly the species info you get when playing one and checking the species info does not say that you are immune to radiation.

#### Steps to reproduce
Create char with Vasilissan species, expose to radiation, get sick, die to radiation as a radiation proof spider person

#### Length of time in which bug has been known to occur

Unknown discoverd in given round -V-

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 3c4106efc581b544ba8873639a32e92cf4606d2e -  - 2020-05-25
Game ID: b7k-c98o

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by BurgerLUA** [comment]
Not sure if this is a feature or a bug.

**Comment by Roland410** [comment]
Vasilissans were rolled into genemodders, making this a non-issue.
