### ISSUE TITLE
Less-than-lethal ballistic rounds too inaccurate

### ISSUE THREAD

**Issue by OolongCow** [BoHBranch/BoH-Bay#946]
#### Description of issue
Almost all ballistic less-than-lethal ammunition is bugged. For some reason or another, all less-than-lethal ammunition fired from ballistic weapons seems to be _significantly_ less likely to hit the targeted body part than any other type of ammunition. Considering how agony works, you _must_ repeatedly hit the same body part in order to down someone, rendering security's military pistol kit practically worthless. This is not a readily-apparent balance issue, as there is no obvious code reason why they're behaving this way, nor has anyone ever PR'd a nerf to them.

#### Difference between expected and actual behavior
**Expected behavior:** Similar or slightly lower accuracy than an equivalent lethal round type when calculating the body part hit.
**Actual behavior:** Security officers who load rubber rounds into their guns suddenly transform into Stormtroopers and spread the agony to everywhere except the part they're targeting.

#### Steps to reproduce
Click the law-breaking spaceman with rubber rounds loaded.

#### Length of time in which bug has been known to occur
The entirety of BoH's existence.

#### Client version, Server revision & Game ID

**Client:** 512
**Server Revision:** 34e164bffd5d505dbfc73dc856233bdaab83b69f -  - 2020-06-06
**Game ID:** b7x-dcT9

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by bearrrrrrrr** [comment]
Can we get any other details on this? Numbers/examples?

**Comment by OolongCow** [comment]
> Can we get any other details on this? Numbers/examples?

This is the commonly cited reason for rubbers not working correctly that I've heard from four or five different people. @Sparrowbird611 and I are probably going to just going to sit down at some point and magdump rubbers on a test server to figure out the truth, though.

I've started to personally suspect that the 0.7 damage modifier against soft targets on ballistics that I found, coupled with 0 armor penetration when most clothing that does have resists has ballistics and not burn, plus something else we haven't found yet, is why ballistic less-than-lethals underperform compared to smartgun stun shots. Not sure. As I stated in #941 , I don't want to just dump a ton of armor penetration onto rubbers as a bandaid fix when we don't even know the real reason.

**Comment by OolongCow** [comment]
I think I've figured out the reason ballistic less-than-lethals perform so poorly, after having reviewed the code a bit:

The 0.7 multiplier to ballistic damage applied before armor calculations. So with current rubber rounds _claiming_ to do 35 agony, in reality, they would only be doing 24.5 (less than current smartguns), which would have had to then try and pen any resistances the target had. Coupled with ballistic resistance being mildly more common and often higher than laser resistance, not being hitscan, and subconscious bias against them, the common belief is that rubber rounds were bad and inconsistent.

Seeing as this is a code problem, closing this issue and going to attempt to fix it in #941

**Comment by OolongCow** [comment]
Okay, I think I may have finally figured it out. It's a lot simpler and more frustrating than I thought it would be.

There are just outright _more_ defined classes for ballistic armor, and the values for them are higher. The values for the "handgun" classes of ballistic and laser armors are almost 25% higher in the case of ballistics, meaning that an armor that should have "equal" protection against ballistics and lasers _actually_ has a significantly higher value for defending against bullets.

So this isn't a coding bug, it's just the code being incredibly inconsistent and lopsided, and people balancing these weapons not realizing it.

Issue closed, will attempt to solve it in #941
