### ISSUE TITLE
e-cig ammo cannot into wallet

### ISSUE THREAD

**Issue by Tristan63** [BoHBranch/BoH-Bay#948]
#### Description of issue

the fucking e-cig shit sticks that go in the cig can't fucking fit in a wallet

#### Difference between expected and actual behavior

you'd think the fucking tiny ass e-cig cartridge would fit, because the death sticks (ecigs) fit in wallets
in actuality they fucking don't

#### Steps to reproduce
stick ecig in wallet and then cry when you can't stick ecig ammo in wallet 

#### Specific information for locating

locate a fucking cig machine buy ammo for ecig then try to stick in wallet

#### Length of time in which bug has been known to occur

Orleans#3306 and Tetrino#8915 peer pressured me into doing this so its probably a fucking long time

#### Client version, Server revision & Game ID

all of the above 

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by TheOrleans** [comment]
Fixing it in a moment
