### ISSUE TITLE
SEA cannot look at cameras

### ISSUE THREAD

**Issue by Tristan63** [BoHBranch/BoH-Bay#949]
#### Description of issue

SEA before sec access was added, and then taken away, could view almost all camera feeds. Now they can only view a few since sec access from SEAs was disabled.
![image](https://user-images.githubusercontent.com/66579448/83986504-03b2b800-a90b-11ea-896f-dc32ae64273c.png)

#### Difference between expected and actual behavior
You'd expect since before sec access was added to SEAs that they could continue viewing all cameras, but they don't.
Can only view a select amount of cameras, and don't even have cam access to some areas they have access to such as the e-arm and all hall cams.

#### Steps to reproduce
Join as SEA
Pick up a camera monitoring program
Shit piss cum as you can't view pretty much any camera

#### Specific information for locating

Related specifically to an ID modification bug that can be fixed by having your ID modified. Keep in mind, before sec access was added to SEAs, they had all camera access. 

#### Length of time in which bug has been known to occur

This bug has occurred since sec access was removed from SEAs after the ersatz sea announcement.  

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 34e164bffd5d505dbfc73dc856233bdaab83b69f -  - 2020-06-06
Game ID: b7x-dJPK
Current map: NTSS Dagon

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Sparrowbird611** [comment]
While I know you could access all those cameras before hand....

Is this really a bug? If anything, the SEA being able to have all cameras before hand seemed like an oversight, since he shouldn't be staring at the camera system all day like some ghetto AI.

**Comment by Tristan63** [comment]
neither should BO, XO, CO, or PADV then because they're not ai

**Comment by TheOrleans** [comment]
This is probably (more than probably) an easy fix, but I don't think it's an issue, probably intended. Let's wait for Burger/Carl response

**Comment by Roland410** [comment]
This is technically not a bug, and a PR changing it should be made instead.
