### ISSUE TITLE
Deck officer doesn't have access to Petrov and DO windoor at his own office.

### ISSUE THREAD

**Issue by HetNeSS** [BoHBranch/BoH-Bay#982]
#### Description of issue
Deck officer doesn't have access to Petrov as well as DO windoor at his own office. As well as ID card modification program. Even to view installed requisites

#### Difference between expected and actual behavior
He's a deck officer, responsible for all shuttles aboard. He should have it

#### Length of time in which bug has been known to occur

18.06.20, 12:30 gmt+0

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: c7ef869fe9e262f42608689ee46a1281f0772a10 -  - 2020-06-17
Game ID: b7I-cdIg

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by TheOrleans** [comment]
- Petrov is probably not an issue. Petrov is not a shuttle, but a detachable lab.

- DO windoor is an issue, EASY FIX on this one

- ID Mod Program is not an issue. Remember DO is not considered part of Command, and other heads such as CoS don't have access to ID program either.

**Comment by Roland410** [comment]
Technically I made the DO the head of supply, but in my rework it'll be properly addressed and made a full member of the heads of staff.

**Comment by Kaksisilma** [comment]
Windoor error fixed. The other two are non-issues
