### ISSUE TITLE
Bar Slide Door Bug

### ISSUE THREAD

**Issue by albert7076** [BoHBranch/BoH-Bay#987]
#### Description of issue
The sliding door at the Bar can't be opened by any Service Staff

#### Difference between expected and actual behavior
The sliding door should've been able to be opened by Service Staff (i.e Bartender) but it can't, instead I saw a Synth open it (not a Service Staff)

#### Steps to reproduce
Spawn as a service staff (Bartender or Cook) and click on the sliding door of the bar, next to the Mess Hall door

#### Specific information for locating

the sliding door is literally named "Bar"
Desc: A strong door.

#### Length of time in which bug has been known to occur
 Since the update on lawyers and adjucators

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: c7ef869fe9e262f42608689ee46a1281f0772a10 -  - 2020-06-17
Game ID: b7J-b8Wn

#### Issue bingo

- [x ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by therealslimpeek** [comment]
req_acess = list("ACCESS_BRIG") is the problem. These secure windoors are quite buggy and constantly changes the access when something apparently unrelated is modified.

I'll get it patched once my last PR gets merged if someone hadn't yet

**Comment by therealslimpeek** [comment]
Fixed with pr #988
